### ISSUE TITLE
Add chip rotation in editor

### ISSUE THREAD

**Issue by hodytone** [UkrainianBanderasCat/Digital-Logic-Sim2#14]
While playing in the simulator, I realized that I really missed the opportunity to turn a chip 90 degrees.

**Comment by AlphaCodingPilot** [comment]
I dont see how that whould be usefull. It                         could also make it diffucult to diffirenciate between input and output pins

**Comment by hodytone** [comment]
To make vertically connected segment to horizontal bus.
Like this
![зображення](https://user-images.githubusercontent.com/67758024/172877393-3b1dae22-3dc0-4215-8f93-4b5550687b2c.png)

**Comment by AlphaCodingPilot** [comment]
#24
