### ISSUE TITLE
translation issues 

### ISSUE THREAD

**Issue by firecerne** [UkrainianBanderasCat/Digital-Logic-Sim2#66]
When selecting a language, the propositions are folder names and, when restarting the game, this happen :
![image](https://user-images.githubusercontent.com/105079722/179488580-5858bbe3-5dae-4621-95be-37344438f497.png)

**Comment by firecerne** [comment]
also this  
![image](https://user-images.githubusercontent.com/105079722/179488790-699cb1d3-e650-4a33-a96e-f526a42e184d.png)

**Comment by firecerne** [comment]
Also when I go back in the setting after restarting, its written that the selected language is Ukrainian (I selected french)

**Comment by UkrainianBanderasCat** [comment]
Hm, on my laptop all working correctly

**Comment by Masster51** [comment]
i will test it now
